version: "3.9"
services:
  get-forecast:
    image: local:get-forecast
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./src:/var/task
